"""Component 3 generator -- emits a native pgfplots/TikZ 2x2 surrogate LOTO figure.

Writes paper/figures/fig9_loto_pgfplots.tex: a standalone-compilable TikZ document whose
inner `tikzpicture` can also be pasted straight into the manuscript. Nothing is rasterised;
the coordinates are baked into the .tex, so the figure needs no external data file.

Source data
-----------
paper/data/loto_predictions_41configs.csv  -- leave-one-tier-out predictions, 41 configs x 4
                                              targets (each row one seed of one cell)
paper/data/table3_surrogate_cv_41configs.csv -- the R2 and MAPE printed in each panel

Points are aggregated to the 14 method x backbone cells: x is the mean measured value with
an across-seed SD error bar, y is the predicted value. Prediction is constant within a cell
(the surrogate's features are pre-run and seed-independent; the only within-cell variation
found was 9e-16, i.e. float noise), so no y error bar is drawn.

The printed R2 and MAPE are the canonical per-row values from the CV table, computed over all
41 rows rather than the 14 aggregated cells. The caption in the emitted file says so.

    python paper/scripts/make_loto_pgfplots.py
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
PRED = ROOT / 'paper' / 'data' / 'loto_predictions_41configs.csv'
CV = ROOT / 'paper' / 'data' / 'table3_surrogate_cv_41configs.csv'
OUT = ROOT / 'paper' / 'figures' / 'fig9_loto_pgfplots.tex'

# target key -> (panel letter, title, axis unit label, scale factor from stored units)
PANELS = [
    ('accuracy',           'a', 'Accuracy',   r'\%', 100.0),
    ('peak_gpu_memory_gb', 'b', 'Peak VRAM',  r'GB',   1.0),
    ('energy_kwh',         'c', 'Energy',     r'Wh', 1000.0),
    ('wall_clock_seconds', 'd', 'Runtime',    r's',    1.0),
]

PREAMBLE = r"""% ---------------------------------------------------------------------------
% Surrogate leave-one-tier-out evaluation: predicted vs measured, 2x2.
% GENERATED by paper/scripts/make_loto_pgfplots.py -- edit that script, not this file.
%
% Standalone build:   pdflatex fig9_loto_pgfplots.tex
% In the manuscript:  \usepackage{pgfplots}\pgfplotsset{compat=1.18}
%                     then \input{figures/fig9_loto_pgfplots_body} or paste the
%                     tikzpicture below into a figure environment.
%
% Each point is one method x backbone cell: x = mean measured value over seeds with an
% across-seed SD error bar, y = the surrogate's prediction for that cell, made by a model
% that never saw the cell's backbone scale. The dashed line is y = x.
% R^2 and MAPE in each panel are the canonical values from
% paper/data/table3_surrogate_cv_41configs.csv (protocol = loto), computed over all 41
% configurations rather than the 14 aggregated cells shown here.
% ---------------------------------------------------------------------------
\documentclass[border=2pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepgfplotslibrary{groupplots}

% IEEE-ish sizing: 9-10 pt text, thin rules, no chart junk.
\pgfplotsset{
  loto/.style={
    width=4.45cm, height=4.0cm, scale only axis,
    tick label style={font=\footnotesize},   % ~9 pt
    label style={font=\small},               % ~10 pt
    title style={font=\small, align=left},
    axis line style={black!55, line width=0.4pt},
    grid=major, grid style={black!12, line width=0.3pt},
    tick align=outside, tick style={black!55},
    axis on top,
  },
  % semi-transparent stats box, upper-left of each panel
  statbox/.style={
    draw=black!30, fill=white, fill opacity=0.78, text opacity=1,
    rounded corners=1pt, inner sep=2pt, font=\scriptsize, align=left,
    anchor=north west,
  },
}

\begin{document}
\begin{tikzpicture}
\begin{groupplot}[
  loto,
  group style={group size=2 by 2, horizontal sep=1.45cm, vertical sep=1.35cm},
]
"""

PANEL = r"""
%% ---- panel (%(letter)s) %(title)s ----
\nextgroupplot[
  title={(%(letter)s) %(title)s},
  xlabel={Measured (%(unit)s)}, ylabel={Predicted (%(unit)s)},
  xmin=%(lo)s, xmax=%(hi)s, ymin=%(lo)s, ymax=%(hi)s,
]
%% 1:1 identity reference
\addplot[dashed, black!65, line width=0.6pt, forget plot]
  coordinates {(%(lo)s,%(lo)s) (%(hi)s,%(hi)s)};
%% measured (x, with across-seed SD) vs predicted (y)
\addplot[
  only marks, mark=*, mark size=1.35pt,
  mark options={fill=black!70, draw=black!70},
  error bars/.cd, x dir=both, x explicit,
  error bar style={black!45, line width=0.4pt}, error mark size=1pt,
] table[x=x, y=y, x error=ex] {
x y ex
%(rows)s};
\node[statbox] at (rel axis cs:0.035,0.965)
  {$R^2=%(r2)s$\\MAPE $=%(mape)s\%%$};
"""

CLOSE = r"""
\end{groupplot}
\end{tikzpicture}
\end{document}
"""


def main():
    pred = pd.read_csv(PRED)
    cv = pd.read_csv(CV)
    cv = cv[cv['protocol'] == 'loto'].set_index('target')

    body = PREAMBLE
    for target, letter, title, unit, scale in PANELS:
        d = pred[pred['target'] == target].copy()
        d['actual'] *= scale
        d['predicted'] *= scale

        cells = (d.groupby(['backbone', 'method'])
                   .agg(x=('actual', 'mean'), ex=('actual', 'std'),
                        y=('predicted', 'mean'))
                   .fillna({'ex': 0.0})            # a 2-seed cell still has an SD; guard anyway
                   .reset_index())

        lo = min(cells['x'].min(), cells['y'].min())
        hi = max((cells['x'] + cells['ex']).max(), cells['y'].max())
        pad = 0.08 * (hi - lo)
        lo, hi = lo - pad, hi + pad

        rows = ''.join('%.6g %.6g %.6g\n' % (r.x, r.y, r.ex)
                       for r in cells.itertuples())

        stat = cv.loc[target]
        body += PANEL % {
            'letter': letter, 'title': title, 'unit': unit,
            'lo': '%.6g' % lo, 'hi': '%.6g' % hi, 'rows': rows,
            'r2': '%.3f' % float(stat['R2']),
            'mape': '%.1f' % float(stat['MAPE_pct']),
        }

    body += CLOSE
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding='utf-8')

    print('wrote %s' % OUT)
    for target, letter, title, unit, scale in PANELS:
        s = cv.loc[target]
        n = len(pred[pred['target'] == target].groupby(['backbone', 'method']))
        print('  (%s) %-10s %2d cells   R2=%.3f  MAPE=%.1f%%'
              % (letter, title, n, float(s['R2']), float(s['MAPE_pct'])))


if __name__ == '__main__':
    main()
